=== dmzoneill/lm051-cs4146-document-architectures/project 1/book.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT book 
(
    title, 
    authors, 
    publisher, 
    edition?, 
    publishedDate, 
    copyright, 
    isbn, 
    AcquisitionsEditors?,
    projectEditors?,
    coverDesigners?,
    graphicDesigners?,
    principalCompositors?,
    copyEditors?,
    technicalEditors?,
    proofReaders?,
    developmentEditors?,
    indexers?, 
    other?
)>
<!-- begin description of book and child elements -->
<!ATTLIST book category CDATA #REQUIRED>
<!ATTLIST book id CDATA #REQUIRED>
<!ATTLIST book lang CDATA "en">
<!ATTLIST book covertype ( soft | hard ) "soft">

<!ELEMENT title ( #PCDATA )>
<!ATTLIST title lang CDATA "en">

<!ELEMENT authors ( person, address*, email* )+>
<!ELEMENT publisher ( publishername+, address* )>
<!ELEMENT email ( #PCDATA )>
<!ELEMENT publishername ( #PCDATA )>

<!ELEMENT address ( buildingname?, addressnum?, street?, city, state?, country, (zipcode | postcode)? )>
<!ELEMENT buildingname ( #PCDATA )>
<!ELEMENT addressnum ( #PCDATA )>
<!ELEMENT street ( #PCDATA )>
<!ELEMENT city ( #PCDATA )>
<!ELEMENT state ( #PCDATA )>
<!ELEMENT country ( #PCDATA )>
<!ELEMENT zipcode ( #PCDATA )>
<!ELEMENT postcode ( #PCDATA )>

<!ELEMENT edition ( editionnum | year )>
<!ELEMENT editionnum ( #PCDATA )>
<!ELEMENT publishedDate ( date )>
<!ELEMENT copyright ( date*, ( companyname | person )* )>
<!ELEMENT date ( day?, month?, year )>
<!ELEMENT day ( #PCDATA )>
<!ELEMENT month ( #PCDATA )>
<!ELEMENT year ( #PCDATA )>
<!ELEMENT isbn (isbn10|isbn13)+>
<!ELEMENT isbn10 ( #PCDATA )>
<!ELEMENT isbn13 ( #PCDATA )>

<!ELEMENT companyname ( #PCDATA )>
<!ATTLIST companyname lang CDATA "en">
<!ELEMENT person ( firstname, initial?, surname, address?, email? )>
<!ATTLIST person lang CDATA "en">
<!ATTLIST person sex CDATA #IMPLIED>
<!ELEMENT firstname ( #PCDATA )>
<!ELEMENT initial ( #PCDATA )>
<!ELEMENT surname ( #PCDATA )>

<!ELEMENT AcquisitionsEditors ( person+ )>
<!ELEMENT projectEditors ( person+ )>
<!ELEMENT coverDesigners ( person+ )>
<!ELEMENT graphicDesigners ( person+ )>
<!ELEMENT principalCompositors ( person+ )>
<!ELEMENT copyEditors ( person+ )>
<!ELEMENT technicalEditors ( person+ )>
<!ELEMENT proofReaders ( person+ )>
<!ELEMENT indexers ( person+ )>
<!ELEMENT developmentEditors ( person+ )>

<!ELEMENT other ( wwwurl*, picture?, price?, pages )>
<!ELEMENT wwwurl ( #PCDATA )>
<!ELEMENT picture ( #PCDATA )>
<!ELEMENT price ( #PCDATA )>
<!ATTLIST price currency ( EUR | USD | GBP ) "EUR">
<!ELEMENT pages ( #PCDATA )>

=== dmzoneill/lm051-cs4146-document-architectures/project 1/book5.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<?xml-stylesheet href="reset.css" type="text/css"?>
<?xml-stylesheet href="book.css" type="text/css"?>
<book id="book5" category="Programming" covertype="soft" lang="en">
    <title>Professional Ajax</title>
    <authors>
        <person sex="male">
            <firstname>Nicholas</firstname>
            <initial>C</initial>
            <surname>Zakas</surname>                          
        </person>
        <person sex="male">
            <firstname>Jeremy</firstname>
            <surname>McPeak</surname>      
        </person>
        <person sex="male">
            <firstname>Joe</firstname>
            <surname>Fawcett</surname>                          
        </person>
    </authors>
    <publisher>
        <publishername>Wiley Publishing Inc.</publishername>
        <address>
            <addressnum>10475</addressnum>
            <street>Crosspoint Boulevard</street>
            <city>Indianapolis</city>
            <country>United States</country>
            <zipcode>46256</zipcode>
        </address>
    </publisher>
    <publishedDate>
        <date>
            <year>2006</year>
        </date>        
    </publishedDate>
    <copyright>
        <date>
            <year>2006</year>
        </date>
        <companyname>Wiley Publishing</companyname>
    </copyright>
    <isbn>
        <isbn10>0-471-77778-1</isbn10>
        <isbn13>978-0-471-77778-6</isbn13>
    </isbn>
    <other>
        <wwwurl>http://www.wrox.com</wwwurl>
        <wwwurl>http://www.wiley.com</wwwurl>
        <pages>406</pages>
    </other>
</book>

=== dmzoneill/lm051-cs4146-document-architectures/project 1/book4.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<?xml-stylesheet href="reset.css" type="text/css"?>
<?xml-stylesheet href="book.css" type="text/css"?>
<book id="book4" category="Computer Science" covertype="hard" lang="en">
    <title>Structured Computer Organization</title>
    <authors>
        <person sex="male">
            <firstname>Andrew</firstname>
            <initial>S</initial>
            <surname>Tanenbaum</surname>  
            <address>
                <buildingname>Vrije University</buildingname>
                <city>Amsterdam</city>                
                <country>Netherlands</country>          
            </address>                
        </person>
    </authors>
    <publisher>
        <publishername>Pearson Prentice Hall</publishername>
        <address>
            <buildingname>Pearson Prentice Hall</buildingname>
            <street>Upper Saddle River</street>
            <city>New Jersey</city>
            <country>United States</country>
            <zipcode>07458</zipcode>
        </address>
    </publisher>
    <edition>
        <editionnum>5</editionnum>
    </edition>
    <publishedDate>
        <date>
            <year>2006</year>
        </date>
    </publishedDate>
    <copyright>
        <date>
            <year>2006</year>
        </date>
        <companyname>Pearson Prentice Hall</companyname>
    </copyright>
    <isbn>
        <isbn10>0-13-148521-0</isbn10>
    </isbn>
    <copyEditors>        
        <person sex="male">
            <firstname>Michael</firstname>
            <surname>Giacobbe</surname>
        </person>
        <person sex="female">
            <firstname>Lisa</firstname>
            <surname>McDowell</surname>
        </person>
    </copyEditors> 
    <other>
        <pages>757</pages>
    </other>
</book>

=== dmzoneill/lm051-cs4146-document-architectures/project 1/book2.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<?xml-stylesheet href="reset.css" type="text/css"?>
<?xml-stylesheet href="book.css" type="text/css"?>
<book id="book2" lang="en" covertype="soft" category="Anthology">
    <title>The Howard Marks - Book of Dope stories</title>
    <authors>
        <person sex="male">
            <firstname>Howard</firstname>
            <surname>Marks</surname>
        </person>
    </authors>
    <publisher>
        <publishername>Vintage</publishername>
        <address>
            <buildingname>Random House</buildingname>
            <addressnum>21</addressnum> 
            <street>Vauxhall Bridge Road</street>
            <city>London</city> 
            <country>England</country>
            <postcode>SWIV 2SA</postcode>
        </address>
    </publisher>
    <publishedDate>
        <date>
            <year>2001</year>
        </date>
    </publishedDate>
    <copyright>
        <date>
            <year>2001</year>
        </date>
        <person sex="male">
            <firstname>Howard</firstname>
            <surname>Marks</surname>
        </person>
    </copyright>
    <isbn>
        <isbn10>0-09-942855-5</isbn10>
    </isbn>  
    <projectEditors>
        <person sex="female">
            <firstname>Heather</firstname>
            <surname>Talbot</surname>
        </person>
        <person sex="female">
            <firstname>Gretchen</firstname>
            <surname>Uphoff</surname>
        </person>
    </projectEditors>  
    <other>
        <pages>287</pages>
    </other>    
</book>

=== dmzoneill/lm051-cs4146-document-architectures/project 1/book3.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<?xml-stylesheet href="reset.css" type="text/css"?>
<?xml-stylesheet href="book.css" type="text/css"?>
<book id="book3" lang="en" covertype="soft" category="Programming">
    <title>ASP.NET programming with Microsoft VISUAL BASIC.NET Step by Step</title>
    <authors>
        <person sex="male">
            <firstname>Andrew</firstname>
            <initial>G</initial>
            <surname>Duthie</surname>
        </person>
        <email></email>
    </authors>
    <publisher>
        <publishername>Microsoft Press</publishername>
        <address>
            <addressnum>12</addressnum>
            <street>Microsoft way</street>
            <city>Redmond</city>
            <state>Washington</state>
            <country>United States</country>
            <postcode>98052-6399</postcode>
        </address>
    </publisher>
    <publishedDate>
        <date>
            <year>2003</year>
        </date>
    </publishedDate>
    <copyright>
        <date>
            <year>2003</year>
        </date>
        <companyname>Microsoft</companyname>
    </copyright>
    <isbn>
        <isbn10>0-7356-1934-4</isbn10>
    </isbn>
    <technicalEditors>
        <person sex="male">
            <firstname>Tony</firstname>
            <surname>Zhang</surname>
        </person>
    </technicalEditors>    
    <proofReaders>
        <person sex="female">
            <firstname>Jill</firstname>
            <surname>Mazurczyk</surname>
        </person>
    </proofReaders>  
    <other>
        <pages>603</pages>
    </other>    
</book>
